# Generated by Django 4.2.2 on 2023-07-25 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viviendas', '0002_alter_edificio_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='nombrePropietario',
        ),
    ]
